name: 'Create Unity Project'

inputs:
  unityVersion:
    required: true
  projectPath:
    required: false
    default: ''
  manifest:
    required: false
    default: '{}'
runs:
  using: 'composite'
  steps:
    - name: Create directory if not exists
      if: ${{ inputs.projectPath != '' }}
      run: mkdir -p ${{ inputs.projectPath }}
      shell: bash
    - name: Create minimal project folders and ProjectVersion.txt
      working-directory: ${{ inputs.projectPath }}
      run: |
        mkdir Assets
        mkdir Packages
        mkdir ProjectSettings
        echo "m_EditorVersion: ${{ inputs.unityVersion }}" > ProjectSettings/ProjectVersion.txt
      shell: bash
    - name: Create manifest.json
      uses: jsdaniell/create-json@v1.2.3
      with: 
        name: "${{ inputs.projectPath }}/Packages/manifest.json"
        json: ${{ inputs.manifest }}
